name: Lint (Dev)
on:
  pull_request:
    branches:
      - dev
jobs:
  lint-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm ci
      - name: Run Lint script
        run: npm run lint:dev
