name: Test
on:
  pull_request:
    branches:
      - master
      - dev
jobs:
  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm ci
      - name: Run Jest
        run: npm test
